# Generated by Django 4.1.3 on 2023-03-29 05:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_remove_appointment_visited_appointment_visited_staus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='final_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('Pending', 'Pending')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('edb3722f-f4ce-4a2f-9292-a5473dca1053')),
        ),
    ]
