# Generated by Django 4.1.3 on 2023-03-29 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='final_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('8a79abd5-74fe-45ba-95a0-bb579bca88df')),
        ),
    ]
