# Generated by Django 4.1.3 on 2023-03-29 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_alter_appointment_final_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='final_clearance',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('9156c8f8-6795-436a-a5d4-c8780f2a8f56')),
        ),
    ]
