# Generated by Django 4.1.3 on 2023-03-30 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_appointment_security_officer_alter_appointment_ld_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='perm_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('bf306ad4-db98-42da-af81-bfa9f80ecb35')),
        ),
    ]
