# Generated by Django 4.1.3 on 2023-04-01 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0087_alter_appointment_perm_id_alter_appointment_tem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="tem_id",
            field=models.UUIDField(
                default=uuid.UUID("0777f680-7275-43f4-bf90-90c5ffd75d90")
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="employee_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
