# Generated by Django 4.1.3 on 2023-04-02 01:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0088_alter_appointment_tem_id_alter_user_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="forgetmessagerequest",
            name="action_perform",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="tem_id",
            field=models.UUIDField(
                default=uuid.UUID("5757db77-7ea0-4f31-91ee-a755f6e46b2c")
            ),
        ),
    ]
