# Generated by Django 4.1.3 on 2023-04-02 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0089_forgetmessagerequest_action_perform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="tem_id",
            field=models.UUIDField(
                default=uuid.UUID("fb3763f6-7ee7-45d1-a244-f825af897506")
            ),
        ),
        migrations.AlterField(
            model_name="forgetmessagerequest",
            name="action_perform",
            field=models.BooleanField(default=False),
        ),
    ]
